dags:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: nfs-client
    accessMode: ReadWriteMany

  gitSync:
    enabled: true
    repo: https://github.com/amdari/movie-review-project
    branch: master
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: "dags"

logs:

  persistence:
    # Enable persistent volume for storing logs
    enabled: true
    size: 1Gi
    storageClassName: nfs-client
